### ISSUE TITLE
SDK Tracker

### ISSUE THREAD

**Issue by nvgoldin** [lago-project/lago#532]
Tracker for SDK-related issues(for each one will open an issue when relevant)

- [x] Get defaults global configuration for the SDK from somewhere(preferably without adding anything hard-coded variables and keeping `lago generate-config` as the source of truth).
- [x] Allow initializing a prefix from a directory - https://github.com/lago-project/lago/pull/552
- [ ] shift ``do_cmd`` logic to the SDK.

**Comment by nvgoldin** [comment]
- [ ] Configure logging for the SDK.

**Comment by nvgoldin** [comment]
[ ] Add docs - https://github.com/lago-project/lago/pull/551

**Comment by nvgoldin** [comment]
Only thing left is `shift do_cmd logic to the SDK.`, will open another issue to track it. Other tasks were completed.
